"""Per-student feedback PDF generation using reportlab."""
from __future__ import annotations

import io
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)


_styles = getSampleStyleSheet()
_H1 = ParagraphStyle("h1", parent=_styles["Heading1"], fontSize=16, textColor=colors.HexColor("#0f172a"))
_H2 = ParagraphStyle("h2", parent=_styles["Heading2"], fontSize=12, textColor=colors.HexColor("#374151"))
_BODY = ParagraphStyle("body", parent=_styles["BodyText"], fontSize=10, leading=14)
_MUTED = ParagraphStyle("muted", parent=_BODY, textColor=colors.HexColor("#6b7280"), fontSize=9)


def build_feedback_pdf(result: dict[str, Any], meta: dict[str, Any]) -> bytes:
    """Render one student's grading result as a single-page A4 PDF."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
    )
    story: list = []

    student = result.get("student_name") or meta.get("file") or "Student"
    grade   = meta.get("grade", "")
    subject = meta.get("subject", "")
    chapter = meta.get("chapter", "")

    story.append(Paragraph(f"Student feedback — {student}", _H1))
    story.append(Paragraph(f"Grade {grade} • {subject} • {chapter}", _MUTED))
    story.append(Spacer(1, 8))

    marks    = result.get("marks_awarded", 0)
    total    = result.get("marks_total", 0)
    pct      = result.get("percentage", 0)
    story.append(Paragraph(
        f"<b>Score: {marks}/{total} ({pct}%)</b>", _H2))
    story.append(Spacer(1, 6))

    per_q = result.get("per_question") or []
    if per_q:
        data = [["Question", "Marks", "Feedback"]]
        for q in per_q:
            data.append([
                str(q.get("q", "")),
                f"{q.get('marks_awarded', '-')}/{q.get('marks_total', '-')}",
                Paragraph(str(q.get("feedback", "")), _BODY),
            ])
        table = Table(data, colWidths=[28*mm, 22*mm, 120*mm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.HexColor("#3730a3")),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("ALIGN",      (1, 0), (1, -1), "CENTER"),
            ("VALIGN",     (0, 0), (-1, -1), "TOP"),
            ("BOX",        (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
            ("INNERGRID",  (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ]))
        story.append(table)
        story.append(Spacer(1, 10))

    strengths = result.get("strengths") or []
    if strengths:
        story.append(Paragraph("✓ Strengths", _H2))
        for s in strengths:
            story.append(Paragraph(f"• {s}", _BODY))
        story.append(Spacer(1, 6))

    mistakes = result.get("mistakes") or []
    if mistakes:
        story.append(Paragraph("✗ Areas to improve", _H2))
        for m in mistakes:
            story.append(Paragraph(
                f"<b>{m.get('type','')}</b>: {m.get('description','')}", _BODY))
        story.append(Spacer(1, 6))

    suggestion = result.get("suggestion")
    if suggestion:
        story.append(Paragraph("💡 Suggestion", _H2))
        story.append(Paragraph(str(suggestion), _BODY))
        story.append(Spacer(1, 4))

    verifier = result.get("verifier")
    if verifier:
        story.append(Spacer(1, 6))
        story.append(Paragraph("🔍 Verifier check", _H2))
        agree = verifier.get("agrees")
        conf  = verifier.get("confidence", "")
        story.append(Paragraph(
            f"Reviewer {'agrees' if agree else 'disagrees'} — confidence {conf}%. "
            f"{verifier.get('comment','')}", _MUTED))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "Generated by Teacher Tools — review and edit before sharing with the student.",
        _MUTED))

    doc.build(story)
    return buf.getvalue()
